version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:3.6.3
    steps:
      - checkout

      - restore_cache:
          keys:
            - platform-dependencies-{{ checksum "package.json" }}
            - platform-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: platform-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Tests
          command: npm run cover
      - codecov/upload:
          file: coverage/lcov.info
workflows:
  version: 2
  main:
    jobs:
      - build:
        filters:
          branches:
            only: master
